export const items = [
   
    {
        id:6,
        category:"APPLIENCE",
        title:"Laptop",
        imgsrc:"https://www.91-cdn.com/hub/wp-content/uploads/2022/07/Top-laptop-brands-in-India.jpg",
        price:"63,999",
    },
    {
        id:2,
        category:"MOBILES",
        title:"Apple iphone 15 ",
        imgsrc:"https://www.apple.com/newsroom/images/2023/09/apple-unveils-iphone-15-pro-and-iphone-15-pro-max/article/Apple-iPhone-15-Pro-lineup-hero-230912_Full-Bleed-Image.jpg.large.jpg",
        price:"1,45,999",
    },
    {
        id:3,
        category:"TV/LAPTOP",
        title:"Samsung",
        imgsrc:"https://m.media-amazon.com/images/I/71G3w6wIhZL._AC_UF1000,1000_QL80_DpWeblab_.jpg",
        price:"63,500",
    },
    {
        id:4,
        category:"BEAUTY",
        title:"Makeup kit",
        imgsrc:"https://images-cdn.ubuy.co.in/651ec2cfef7c12072476f153-58-colors-professional-makeup-kit-for.jpg",
        price:299,
    },
    {
        id:5,
        category:"TOY",
        title:"Car",
        imgsrc:"https://m.media-amazon.com/images/I/91aVOFkXTBL.jpg",
        price:199,
    },
    {
        id:1,
        category:"FASHION",
        title:"Shirt",
        imgsrc:"https://www.seasonbazaar.com/wp-content/uploads/2019/08/TUNEVUSE-Mens-shirts-Camisa-Masculina-Long-Sleeve-Shirt-Men-Korean-Slim-Design-Formal-Casual-Male-Dress-6.jpg",
        price:"599",
    },
    {
        id:7,
        category:"MEDICINE",
        title:"Paracetamol",
        imgsrc:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnjh7RR86DKoNmr2D9v7TOZds0JtSwbfvO085qtrt7og&s",
        price:50,
    },
    {
        id:8,
        category:"BOOKS",
        title:"CSE",
        imgsrc:"https://rukminim2.flixcart.com/image/850/1000/kihqz680-0/book/j/a/n/a-textbook-of-java-programming-original-imafy9zfafax9kdy.jpeg?q=90&crop=false",
        price:599,
    }
]